/**
 * Competitor Analyzer
 *
 * Automatically analyzes competitors discovered during lead research.
 * Generates PROFILE.md and STEAL-FOR-VIZBIZ.md in the competition folder.
 * Integrates with the lead processing pipeline.
 *
 * Based on the competition-analyzer skill.
 */

import * as fs from "fs";
import * as path from "path";
import { isJunkCompetitor } from "./junk-filter";

export interface CompetitorToAnalyze {
  name: string;
  url?: string;
  mentionCount?: number;
  totalPrompts?: number;
}

export interface CompetitorProfile {
  name: string;
  url: string;
  category: string;
  targetCustomer: string;
  corePromise: string;
  whatTheyDo: string;
  strengths: string[];
  weaknesses: string[];
  whatToSteal: string[];
  whatToAvoid: string[];
  netAssessment: string;
}

export interface AnalysisResult {
  competitor: string;
  profilePath: string;
  stealPath: string;
  addedToSynthesis: boolean;
}

const COMPETITION_DIR = path.resolve(
  process.cwd(),
  "..",
  "competition"
);

const SYNTHESIS_PATH = path.join(COMPETITION_DIR, "FORMULA-SYNTHESIS.md");

// Ensure competition directory exists
function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

/**
 * Analyze a competitor using web research
 * Returns structured profile data
 */
export async function analyzeCompetitor(
  comp: CompetitorToAnalyze,
  niche: string = "general"
): Promise<CompetitorProfile | null> {
  const name = comp.name;
  const url = comp.url || "";

  // Use web search to gather intel about the competitor
  const searchQueries = [
    `"${name}" AI visibility`,
    `"${name}" GEO audit service`,
    `"${name}" features pricing`,
    `"${name}" reviews`,
  ];

  // For now, return a structured template that gets enriched
  // The actual enrichment happens via the research-runner context
  const profile: CompetitorProfile = {
    name,
    url,
    category: "AI visibility / GEO service",
    targetCustomer: "businesses seeking AI search visibility",
    corePromise: "help businesses appear in AI-driven search results",
    whatTheyDo: "",
    strengths: [],
    weaknesses: [],
    whatToSteal: [],
    whatToAvoid: [],
    netAssessment: "",
  };

  return profile;
}

/**
 * Generate PROFILE.md content for a competitor
 */
export function generateProfileMarkdown(
  profile: CompetitorProfile,
  mentionCount: number,
  totalPrompts: number,
  niche: string
): string {
  const safeName = profile.name.replace(/[^a-zA-Z0-9]/g, "-");
  const date = new Date().toISOString().split("T")[0];

  let md = `# ${profile.name} — Competitor Profile\n\n`;
  md += `- **URL:** ${profile.url || "Unknown"}\n`;
  md += `- **Category:** ${profile.category}\n`;
  md += `- **Target customer:** ${profile.targetCustomer}\n`;
  md += `- **Core promise:** ${profile.corePromise}\n`;
  md += `- **Niche relevance:** ${niche}\n`;
  md += `- **Discovered via:** Lead research pipeline (${mentionCount}/${totalPrompts} prompt appearances)\n`;
  md += `- **Analyzed:** ${date}\n\n`;

  md += `## What They Do\n${profile.whatTheyDo || "Analysis pending."}\n\n`;

  md += `## Strengths\n`;
  if (profile.strengths.length > 0) {
    for (const s of profile.strengths) {
      md += `- ${s}\n`;
    }
  } else {
    md += `- To be analyzed\n`;
  }
  md += `\n`;

  md += `## Weaknesses / Gaps\n`;
  if (profile.weaknesses.length > 0) {
    for (const w of profile.weaknesses) {
      md += `- ${w}\n`;
    }
  } else {
    md += `- To be analyzed\n`;
  }
  md += `\n`;

  md += `## Net Assessment\n${profile.netAssessment || "Analysis pending."}\n\n`;
  md += `## Source\nAuto-generated by VizBiz lead pipeline on ${date}.\n`;

  return md;
}

/**
 * Generate STEAL-FOR-VIZBIZ.md content for a competitor
 */
export function generateStealMarkdown(
  profile: CompetitorProfile,
  niche: string
): string {
  const date = new Date().toISOString().split("T")[0];

  let md = `# ${profile.name} — What VizBiz Should Steal\n\n`;
  md += `## Strategic Read\n`;
  md += `Discovered via lead pipeline research in the ${niche} niche.\n`;
  md += `This competitor appeared frequently in AI recommendation prompts — they are getting surfaced.\n\n`;

  md += `## What to Steal Now\n`;
  if (profile.whatToSteal.length > 0) {
    for (let i = 0; i < profile.whatToSteal.length; i++) {
      md += `### ${i + 1}. ${profile.whatToSteal[i]}\n\n`;
    }
  } else {
    md += `Analysis pending — run competition-analyzer skill for full breakdown.\n\n`;
  }

  md += `## What Not to Copy\n`;
  if (profile.whatToAvoid.length > 0) {
    for (const a of profile.whatToAvoid) {
      md += `- ${a}\n`;
    }
  } else {
    md += `- To be analyzed\n`;
  }
  md += `\n`;

  md += `## Bottom Line\n`;
  md += `This competitor gets recommended by AI systems in the ${niche} vertical. `;
  md += `Their presence in prompt results means they have AI visibility strength we can learn from.\n\n`;
  md += `## Source\nAuto-generated by VizBiz lead pipeline on ${date}.\n`;

  return md;
}

/**
 * Write competitor files to disk and update synthesis
 */
export async function writeCompetitorAnalysis(
  profile: CompetitorProfile,
  mentionCount: number,
  totalPrompts: number,
  niche: string
): Promise<AnalysisResult> {
  const safeName = profile.name.replace(/[^a-zA-Z0-9]/g, "-");
  const compDir = path.join(COMPETITION_DIR, safeName.toLowerCase());
  ensureDir(compDir);

  const profileMd = generateProfileMarkdown(profile, mentionCount, totalPrompts, niche);
  const stealMd = generateStealMarkdown(profile, niche);

  const profilePath = path.join(compDir, "PROFILE.md");
  const stealPath = path.join(compDir, "STEAL-FOR-VIZBIZ.md");

  // Don't overwrite existing detailed profiles
  if (fs.existsSync(profilePath)) {
    const existing = fs.readFileSync(profilePath, "utf-8");
    if (existing.length > 500) {
      // Already has substantial content — skip overwrite, just update mention count
      console.info(`[competitor-analyzer] ${profile.name} already profiled (${existing.length} chars) — skipping`);
      return {
        competitor: profile.name,
        profilePath,
        stealPath,
        addedToSynthesis: false,
      };
    }
  }

  fs.writeFileSync(profilePath, profileMd);
  fs.writeFileSync(stealPath, stealMd);
  console.info(`[competitor-analyzer] Wrote ${profilePath} and ${stealPath}`);

  // Update synthesis
  let addedToSynthesis = false;
  try {
    addedToSynthesis = updateSynthesis(profile.name, profile.category, niche);
  } catch (err) {
    console.warn("[competitor-analyzer] Failed to update synthesis:", err);
  }

  return {
    competitor: profile.name,
    profilePath,
    stealPath,
    addedToSynthesis,
  };
}

/**
 * Add competitor to FORMULA-SYNTHESIS.md if not already tracked
 */
function updateSynthesis(name: string, category: string, niche: string): boolean {
  if (!fs.existsSync(SYNTHESIS_PATH)) {
    return false;
  }

  const content = fs.readFileSync(SYNTHESIS_PATH, "utf-8");

  // Check if already tracked
  if (content.toLowerCase().includes(name.toLowerCase())) {
    return false;
  }

  // Find the "Current competitor coverage" section and append
  const marker = "## Current competitor coverage";
  const idx = content.indexOf(marker);
  if (idx < 0) {
    return false;
  }

  const entry = `- ${name}: discovered via lead pipeline (${niche}); ${category}\n`;
  const updated = content.slice(0, idx + marker.length) + "\n" + entry + content.slice(idx + marker.length);

  fs.writeFileSync(SYNTHESIS_PATH, updated);
  console.info(`[competitor-analyzer] Added ${name} to FORMULA-SYNTHESIS.md`);
  return true;
}

/**
 * Run competitor analysis on the top N competitors from research results
 * Called from process-lead after research completes
 */
export async function analyzeTopCompetitors(
  promptResults: Array<{
    competitorName?: string;
    competitorAppeared?: boolean;
  }>,
  niche: string,
  topN: number = 3
): Promise<AnalysisResult[]> {
  // Count competitor appearances
  const compCounts: Record<string, number> = {};
  for (const p of promptResults) {
    if (p.competitorName && p.competitorAppeared) {
      compCounts[p.competitorName] = (compCounts[p.competitorName] || 0) + 1;
    }
  }

  // Filter out junk competitors
  const filtered = Object.entries(compCounts)
    .filter(([name]) => !isJunkCompetitor(name))
    .sort(([, a], [, b]) => b - a)
    .slice(0, topN);

  if (filtered.length === 0) {
    console.info("[competitor-analyzer] No valid competitors to analyze");
    return [];
  }

  const totalPrompts = promptResults.length;
  const results: AnalysisResult[] = [];

  for (const [name, count] of filtered) {
    const profile: CompetitorProfile = {
      name,
      url: "",
      category: `${niche} — AI visibility competitor`,
      targetCustomer: niche.replace(/_/g, " "),
      corePromise: "Appears frequently in AI recommendation prompts",
      whatTheyDo: `Discovered as a top competitor in ${niche} research. Appeared in ${count}/${totalPrompts} AI recommendation prompts.`,
      strengths: [`Gets recommended by AI systems (${count}/${totalPrompts} appearances)`],
      weaknesses: ["Detailed analysis pending — run competition-analyzer skill for full breakdown"],
      whatToSteal: ["Study their web presence — structure, content, schema markup, entity clarity"],
      whatToAvoid: ["Unknown — detailed analysis needed"],
      netAssessment: `Frequent AI recommendation presence makes them worth studying. They are doing something right for AI visibility in the ${niche} space.`,
    };

    try {
      const result = await writeCompetitorAnalysis(profile, count, totalPrompts, niche);
      results.push(result);
    } catch (err) {
      console.warn(`[competitor-analyzer] Failed to analyze ${name}:`, err);
    }
  }

  console.info(`[competitor-analyzer] Analyzed ${results.length} competitors`);
  return results;
}
