import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";

export const metadata: Metadata = {
  title: "AI Visibility for Car Dealerships FAQ | VizBiz",
  description:
    "Answers to common dealership questions about AI visibility, inventory, reviews, service pages, competitor comparisons, and audits.",
};

const faqItems = [
  {
    question: "What is AI visibility for automotive retailers?",
    answer:
      "AI visibility is how often a dealership appears in answers generated by AI systems such as ChatGPT, Perplexity, Google AI experiences, and similar tools.",
  },
  {
    question: "How do dealerships show up in ChatGPT results?",
    answer:
      "Dealerships show up when AI systems can clearly understand inventory, trust signals, services, local relevance, and buyer-answer content.",
  },
  {
    question: "Does inventory affect AI visibility?",
    answer:
      "Yes. Inventory structure, pricing clarity, model information, and local relevance all affect whether AI systems can confidently surface a dealership for used or model-specific queries.",
  },
  {
    question: "Do reviews affect AI visibility?",
    answer:
      "Yes. Review quality, detail, recency, and consistency help AI systems decide whether a dealership is trustworthy enough to recommend.",
  },
  {
    question: "Can service pages improve AI visibility?",
    answer:
      "Yes. Strong service pages, service FAQs, and clear maintenance content help dealerships appear for service-intent and ownership-intent prompts.",
  },
  {
    question: "What does an AI visibility audit include?",
    answer:
      "An AI visibility audit shows where the dealership appears, where competitors appear instead, which categories are weak, and what should be improved first.",
  },
  {
    question: "How can a dealership improve visibility for 'cheap used car near me' type searches?",
    answer:
      "Improve inventory structure, pricing clarity, financing support content, local relevance, and used inventory theme pages tied to affordability and buyer-intent language.",
  },
  {
    question: "Why are competitors showing up instead of my dealership?",
    answer:
      "Competitors may have stronger inventory signals, better reviews, clearer service or financing explanations, stronger FAQ coverage, or better local relevance in the exact prompt category the buyer is using.",
  },
];

const relatedPages = [
  {
    title: "AI Visibility for Automotive Retailers",
    href: "/ai-visibility-for-car-dealerships",
    description: "Definition page explaining what AI visibility means for dealerships.",
  },
  {
    title: "How Dealerships Show Up in AI Search",
    href: "/how-dealerships-show-up-in-ai-search",
    description: "Explains the signals AI systems use when choosing which dealerships to mention.",
  },
  {
    title: "AI Visibility Audit for Automotive Retailers",
    href: "/ai-visibility-audit-for-car-dealerships",
    description: "Shows what the audit includes and how competitor gaps are revealed.",
  },
  {
    title: "Cheap Used Car Near Me: AI Visibility for Dealerships",
    href: "/cheap-used-car-near-me-ai-visibility-for-dealerships",
    description: "Focused page on affordability prompts, inventory visibility, and buyer-intent language.",
  },
  {
    title: "Sample AI Visibility Report for Automotive Retailers",
    href: "/sample-ai-visibility-report-for-car-dealerships",
    description: "Shows what a dealership actually receives from a sample report and recommendation set.",
  },
];

export default function FaqAiVisibilityForCarDealershipsPage() {
  return (
    <main className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)]">
      <SiteHeader ctaLabel="Get My Snapshot" />

      <section className="section-shell px-4 pb-16 pt-14 sm:px-6 sm:pb-20 sm:pt-18 lg:px-8 lg:pb-24 lg:pt-20">
        <div className="mx-auto max-w-4xl">
          <div className="section-kicker">FAQ hub</div>
          <h1 className="display-font mt-6 text-[2.8rem] font-semibold leading-[0.96] tracking-[-0.05em] sm:text-[4rem]">
            FAQ: AI Visibility for Automotive Retailers
          </h1>

          <div className="glass-card mt-10 rounded-[2rem] p-6 sm:p-8">
            <p className="text-base leading-8 text-[var(--text-secondary)] sm:text-lg">
              This page answers the questions dealerships are most likely to ask about AI visibility, AI-driven search inclusion, competitor visibility, inventory relevance, and audit value.
            </p>
          </div>
        </div>
      </section>

      <section className="section-shell border-t border-white/6 px-4 py-16 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <div className="space-y-4">
            {faqItems.map((item) => (
              <div key={item.question} className="glass-card rounded-[1.75rem] p-6 sm:p-7">
                <h2 className="text-xl font-semibold leading-8 sm:text-2xl">{item.question}</h2>
                <p className="mt-4 text-base leading-8 text-[var(--text-secondary)] sm:text-lg">
                  {item.answer}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section-shell border-t border-white/6 px-4 py-16 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <h2 className="display-font text-[2rem] font-semibold tracking-[-0.04em] sm:text-[2.6rem]">
            Related pages
          </h2>
          <div className="mt-8 grid gap-4 sm:grid-cols-2">
            {relatedPages.map((page) => (
              <Link key={page.href} href={page.href} className="metric-row rounded-2xl p-5 transition hover:border-[var(--border-subtle)] hover:bg-white/6">
                <h3 className="text-lg font-semibold">{page.title}</h3>
                <p className="mt-3 text-sm leading-7 text-[var(--text-secondary)]">{page.description}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="section-shell border-t border-white/6 px-4 py-16 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <div className="cta-shell rounded-[2rem] px-6 py-10 sm:px-10 sm:py-12">
            <div className="section-kicker">Get your snapshot</div>
            <h2 className="display-font mt-5 text-[2.2rem] font-semibold tracking-[-0.05em] sm:text-[3rem]">
              Get Your AI Visibility Snapshot
            </h2>
            <p className="mt-5 text-base leading-8 text-[var(--text-secondary)] sm:text-lg">
              See how your dealership appears in AI-driven search, where competitors are showing up more often today, and what to improve first.
            </p>
            <div className="mt-8">
              <Link href="/intake" className="premium-button rounded-2xl px-6 py-3.5 text-sm font-semibold">
                Get My AI Visibility Snapshot
              </Link>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
